version: '3.3'
services:
  product-service:
    build:
      context: ./microProducts
    ports:
      - '4000:3000'
    networks:
      - microservices
  review-service:
    build:
      context: ./microReviews
    ports:
      - '4001:3000'
    networks:
      - microservices
networks:
  microservices:
